name: Normal
favicon: null
layout_spectrum: 0.49416
typography_spectrum: 0.3153457
title: Normal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#dddddd'
    - '#191919'
    - '#969696'
    - '#464646'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
