name: Normal
favicon: null
layout_spectrum: 0
typography_spectrum: 0.30133
title: Normal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#dddddd'
    - '#191919'
    - '#969696'
    - '#464646'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
