name: Normal
favicon: null
layout_spectrum: 0.98331
typography_spectrum: 0.3153457
title: Normal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#dbdbdb'
    - '#fefefe'
    - '#96704b'
    - '#502f1e'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
